polling/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.index, name="index"),
]

polling/polling/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polling/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
  path('', views.index, name="index"),
  path('<int:question_id>/', views.detail, name="detail"),
  path('<int:question_id>/results/', views.results, name="results"),
  path('<int:question_id>/vote/', views.vote, name="vote")
]

polling/pages/models.py
from django.db import models

# Create your models here.

polling/polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  vote = models.IntegerField(default=0)

  def __str__(self):
    return self.choice_text

polling/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(req):
    return render (req, 'pages/index.html')

polling/polls/views.py
from django.shortcuts import get_object_or_404, render
from .models import Question, Choice
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def index(req):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {"latest_question_list": latest_question_list}
    return render(req, "polls/index.html", context)

def detail(req, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exists")
    return render(req, 'polls/detail.html', {"question": question})

def results(req, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(req, "polls/results.html", {"question": question})

def vote(req, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=req.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(req, "polls/detail.html", {"question": question, "error_message": "Please select a choice", })
    else:
        selected_choice.vote += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

polling/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <title>Polling App {% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'partials/_navbar.html' %}
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">{% block content %}{% endblock %}</div>
      </div>
    </div>
  </body>
</html>

polling/templates/pages/index.html
{% extends 'base.html' %} {% block content %}

<div class="card text-center">
  <div class="card-body">
    <h1>Welcome to Polling App</h1>
    <p>This is Django mini app</p>
    <a href="{% url 'polls:index' %}" class="btn btn-dark">Polling (Active)</a>
  </div>
</div>

{% endblock %}

polling/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
  <div class="containter"><a href="/" class="navbar-brand">Polling App</a></div>
</nav>

polling/templates/polls/detail.html
{% extends 'base.html' %} {% block content %}
<a href="{% url 'polls:index' %}" class="btn btn-secondary btn-sm mb-3"
  >Back to Polls</a
>

<h1 class="text-center mb-3">{{question.question_text}}</h1>

{% if error_message %}
<p class="alert alert-danger">
  <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %} {% for choice in question.choice_set.all %}
  <div class="form-check">
    <input
      type="radio"
      name="choice"
      class="form-check-input"
      id="choice{{ forloop.counter }}"
      value="{{ choice.id }}"
    />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
  </div>
  {% endfor %}
  <input
    type="submit"
    value="vote"
    class="btn btn-success btn-lg btn-block mt-4"
  />
</form>

{% endblock %}

polling/templates/polls/index.html
{% extends 'base.html' %} {% block content %}
<h1 class="text-center mb-3">Poll Questions</h1>
{% if latest_question_list %} {% for question in latest_question_list %}
<div class="card mb-3">
  <div class="card-body">
    <p class="lead">{{ question.question_text }}</p>
    <a
      href="{% url 'polls:detail' question.id %}"
      class="btn btn-primary btn-sm"
    >
      Vote Now</a
    >
    <a
      href="{% url 'polls:results' question.id %}"
      class="btn btn-secondary btn-sm"
    >
      Results</a
    >
  </div>
</div>
{% endfor %} {% else %}
<p>No Polls Available</p>
{% endif %} {% endblock %}

polling/templates/polls/results.html
{% extends 'base.html' %} {% block content %}

<h1 class="mb-5 text-center">{{question.question_text}}</h1>

<ul class="list-group mb-5">
  {% for choice in question.choice_set.all %}
  <li class="list-group-item">
    {{choice.choice_text}}
    <span class="badge badge-success float-right"
      >{{choice.vote}} vote{{choice.vote | pluralize}}</span
    >
  </li>
  {% endfor %}
</ul>

<a href="{% url 'polls:index' %}" class="btn btn-secondary">Back to Polls</a>
<a href="{% url 'polls:detail' question.id %}" class="btn btn-dark"
  >Vote again?</a
>
{% endblock %}